### ISSUE TITLE
Mac客户端白屏

### ISSUE THREAD

**Issue by shuiRong** [geph-official/geph2#10]
OSX Catalina
Geph GUI 版本3.0.1 (3.0.1)

![image](https://user-images.githubusercontent.com/16076993/70536762-4ed95180-1b9a-11ea-8317-a0468b565102.png)

**Comment by nullchinchilla** [comment]
確實不是第一次遇到這個錯誤報告。

我自己沒有蘋果電腦，比較難以測試。但會儘快修復

**Comment by nullchinchilla** [comment]
應該已在3.0.7解決。

**Comment by shuiRong** [comment]
实测的确解决了。
