### ISSUE TITLE
每次启动提示 Network error

### ISSUE THREAD

**Issue by hmyzero** [geph-official/geph2#12]
![Annotation 2019-12-11 120022](https://user-images.githubusercontent.com/58760106/70590545-0a879900-1c0e-11ea-9444-24516121257a.png)

每次启动时都会提示 Network error，版本3.0.3, 3.0.4都是，确定后不影响正常使用。

简体中文Win10 1909，中国联通宽带

**Comment by nullchinchilla** [comment]
这个是检查升级时报的错。检查升级用的是GitHub，最近被墙搞小动作不少。

下一个版本会解决。有可能需要手动升级，我这里或发信息

**Comment by nullchinchilla** [comment]
这个问题应该解决了，升级到3.0.5
