### ISSUE TITLE
Mizaru这个算法在哪里哪

### ISSUE THREAD

**Issue by dyhack** [geph-official/geph2#2]
Mizaru这个算法在哪里哪

**Comment by nullchinchilla** [comment]
还没有写详细说明。可以找代码里ticket相关的

**Comment by dyhack** [comment]
好吧，你赢了。

**Comment by dyhack** [comment]
或者关于你的那个算法有相关的论文参考吗

**Comment by nullchinchilla** [comment]
和这个协议基本雷同： https://privacypass.github.io/

**Comment by dyhack** [comment]
![image](https://user-images.githubusercontent.com/22422580/70287178-07a13880-1809-11ea-8514-4893ff972d67.png)
你的程序报错啦

**Comment by nullchinchilla** [comment]
这个错误是登录超时，因为CDN连接不上。我会尽快改进

**Comment by nullchinchilla** [comment]
#6
