### ISSUE TITLE
geph-exit panic in singleHop mode

### ISSUE THREAD

**Issue by stigggy** [geph-official/geph2#22]
$./geph-exit` -singleHop :5000
INFO[0000] <<< ENTERING SINGLE HOP MODE >>>
INFO[0000] ... All other arguments will be ignored!
INFO[0000] ... PK = <my PK>
INFO[0000] ... TCP on [::]:5000
INFO[0000] ... UDP on [::]:5000
DEBU[0433] SH client [UDP roaming] @ osid-c30d1f8b0e08ac96eb07
DEBU[0433] [osid-c30d1f8b0e08ac96eb07] accept
DEBU[0433] [osid-c30d1f8b0e08ac96eb07] close
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x81b226]

goroutine 19 [running]:
main.handle(0x9cdbe0, 0xc000075520)
        /home/miyuruasuka/Geph2/gephng-binaries/geph2/cmd/geph-exit/handle.go:134 +0x4e6
created by main.shUDP
        /home/miyuruasuka/Geph2/gephng-binaries/geph2/cmd/geph-exit/singlehop.go:65 +0x31b

**Comment by lex-yacc** [comment]
INFO[0000] ... PK =

PK should not be empty.
see: 
[https://github.com/geph-official/geph2/wiki/Advanced-usage](url)
Server setup
