### ISSUE TITLE
Android 5.0 和 6.0无法运行，麻烦了。

### ISSUE THREAD

**Issue by ChinaSakhalin** [geph-official/geph2#29]
Android 5.0 和 Android 6.0 系统，安装好迷雾通运行后，不出现登陆界面，白屏，只有顶部的状态栏显示，但是如果有更新，可以点击通知栏的条目下载安装，更新之后依然是白屏。
Android 8.0 完全没问题。
麻烦了，非常感谢！

**Comment by nullchinchilla** [comment]
https://github.com/geph-official/geph2/wiki/FAQ-%5B%E4%B8%AD%E6%96%87%5D
这是因为webview版本的问题。
