### ISSUE TITLE
TCP-based transport?

### ISSUE THREAD

**Issue by nullchinchilla** [geph-official/geph2#3]
UDP might run into rate limiting and such, but TCP has poor roaming support. What we need is:

- A "roaming TCP" transport protocol. This requires some sort of ACK system to know where to resume.
- Automatically detect network changes and reconnect. 

This might not be necessary though. Proper benchmarks are needed.

**Comment by nullchinchilla** [comment]
One hack could just be KCP-X over TCP over ScrambleSuit. That way roaming isn't such a biggie.

A better approach might be to do a proper multipath-TCP type protocol, where the onion routing is actually on unordered packets rather than streams, and KCP-X is end-to-end. That way, TCP and UDP bridges would just be "physical links" and complex ad-hoc logic wouldn't be needed.

We should investigate how multipath TCP works.

**Comment by nullchinchilla** [comment]
One thing we could do is actually introduce "TCP primacy", and have clients connect over ScrambleSuit to negotiate KCP-X sessions on other ports both over TCP and UDP. This might have fingerprinting implications, but it'll also simplify the really brittle N4 handshake logic that's the source of countless bugs.

A more backwards-compatible approach might actually be N4/UDP-X primacy, but that does require more long-term maintenance of the crappy N4 handshake and crypto code. In any case the "subsidiary" streams would have really simple crypto since no handshakes are needed anymore.

**Comment by NoneSloth** [comment]
I have not read the code yet, but if all geph need is an unreliable datagram, can we use raw socket with fake TCP headers?

In that way, we have all benefits of UDP (roaming, better latency with TCP-over-UDP), and at the same time, we can make the router thinks that we are sending TCP segments.

Not an expert, just wondering if this is doable.

**Comment by nullchinchilla** [comment]
Custom/fake TCP is bad since it's a fingerprint that can be used to identify and block Geph.

**Comment by nullchinchilla** [comment]
A TCP-first approach has been pushed in e4639b21. In a future version of gephgui, clients will always first connect via TCP to bridges and then negotiate the next protocol.
