### ISSUE TITLE
请问可以提供对5x等旧版本Webview的支持吗？

### ISSUE THREAD

**Issue by ChinaSakhalin** [geph-official/geph2#31]
只是咨询一下，因为尝试过升级，但由于手机系统的原因实在做不到，特来请教一下可否提供支持，谢谢。

**Comment by nullchinchilla** [comment]
安卓4.4之后的webview应该是可以独立于系统升级的。可以试试升级webview。

我确实仍然没有发现到底是什么功能旧webview上没有，需要给gephgui加上什么polyfill。如果有什么想法的话欢迎贡献！

**Comment by ChinaSakhalin** [comment]
升级了3.4.0版本，发现连旧的4x系列都可以用了，不知道中间是否错过了其他版本。总之很感谢，可以用了，希望能延长一定时间支持旧版本webview吧，会推给别人。

**Comment by nullchinchilla** [comment]
已经可以了。
