### ISSUE TITLE
linux下用了一段时间后，出现Bad Sock5 Request

### ISSUE THREAD

**Issue by pslean** [geph-official/geph2#34]
日志如下：
DEBU[0168] [5] opened google.com.hk:443 in 2.053960459s 
DEBU[1808] Bad SOCKS5 request: SOCKS error: 8           
DEBU[1866] Bad SOCKS5 request: SOCKS error: 8           
DEBU[1954] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2073] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2290] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2597] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2644] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2649] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2731] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2847] Bad SOCKS5 request: SOCKS error: 8           
DEBU[2852] Bad SOCKS5 request: SOCKS error: 8           
DEBU[3052] Bad SOCKS5 request: SOCKS error: 8

**Comment by nullchinchilla** [comment]
这应该不是bug。影响使用吗？
