### ISSUE TITLE
win 7 迷雾通退出时能把代理设置还原吗

### ISSUE THREAD

**Issue by sd4337902** [geph-official/geph2#38]
win7使用退出迷雾通后，打开游览器显示代理服务器异常。能退出时自动把代理设置还原一下吗。不然我给别人推荐这款软件的时候只能表示：“安装这款软件以后电脑不打开软件就再也无法连接网络”，不利于推广

**Comment by nullchinchilla** [comment]
不应该啊，关闭迷雾通时会自动还原代理设置

**Comment by malagebidi** [comment]
Win10我测试了，关闭迷雾通后系统代理设置没有还原。
