### ISSUE TITLE
分流问题

### ISSUE THREAD

**Issue by MrPeterJin** [geph-official/geph2#39]
分流功能还需进一步完善。使用时发现即使开启分流功能时，访问国内大学网站时流量仍然会经过代理。

**Comment by ElTopo** [comment]
@MrPeterJin 如果自己編譯的話，可以自行修改 cmd/geph-client/chinalist/chinalist.go 把你訪問的國内大學網站域名加進表中。

**Comment by MrPeterJin** [comment]
好的，谢谢您，已经解决，不过还是希望geph官方集成一个自定义白名单功能

**Comment by nullchinchilla** [comment]
另外，欢迎对generate.rkt进行pull request增加更多的国内网站
