### ISSUE TITLE
把迷雾通作为一个上层的 socks5 代理时，遇到 handShake failed: socks version not supported 问题

### ISSUE THREAD

**Issue by leyle** [geph-official/geph2#40]
使用 迷雾通作为一个上层的 socks5 代理，用 spit/shuttle 这样的支持 socks5 的代理软件来连接时，就会遇到这个问题。 sipt/shuttle 连接 shadosocksx-ng 就不会出现问题，我猜可能是迷雾通的某些协议与 socks5 的不一致？

**Comment by nullchinchilla** [comment]
你确定是SOCKS5而非SOCKS4吗？

**Comment by leyle** [comment]
> 你确定是SOCKS5而非SOCKS4吗？
我找到原因了，程序发送死锁崩溃，导致下层代理没有响应。抛了个这个错误。
实质是迷雾通的程序 goroutine 发生死锁了。

**Comment by nullchinchilla** [comment]
> > 你确定是SOCKS5而非SOCKS4吗？
> > 我找到原因了，程序发生死锁崩溃，导致下层代理没有响应。抛了个这个错误。
> > 实质是迷雾通的程序 goroutine 发生死锁了。

能否发一下日志？死锁是bug啊

**Comment by leyle** [comment]
[stacktrace.txt](https://github.com/geph-official/geph2/files/4322035/stacktrace.txt)

你看一下这个，不知道这个文件能否有帮助。

我使用的模式是 浏览器 -> sipt/shuttle -> 迷雾通(socks5)

另外还有个问题，有些 https 网站打开后，网站的证书变成了另外的网站的了，有说是 dns 污染，我更改了 dns 还是这样的。换了 shadowsocksX-NG 生成的 socks5 就没有问题。所以我怀疑是你这边的问题。
