### ISSUE TITLE
新用户提问，没法注册

### ISSUE THREAD

**Issue by mmiker** [geph-official/geph2#48]
CAPTCHA上面的转圈一直没停，没法注册新用户。试过直接连接， 全局HTTP代理，VPN,都没用。
![1](https://user-images.githubusercontent.com/7027280/80305976-e6120f00-87f2-11ea-8b14-41559db58e27.png)

**Comment by briteming** [comment]
我挂vpn后，注册成功

**Comment by nullchinchilla** [comment]
这应该是暂时的网络问题
