### ISSUE TITLE
Azure CDN really slow on some ISPs

### ISSUE THREAD

**Issue by nullchinchilla** [geph-official/geph2#6]
Multiple users have noticed errors like this:

![](https://user-images.githubusercontent.com/22422580/70287178-07a13880-1809-11ea-8514-4893ff972d67.png)

This is probably because the binder is slow. Fixing the binder transport to include things other than Azure domain fronting will fix this.

**Comment by nullchinchilla** [comment]
One short-term fix would be to add some other CDN providers. Candidates include:
- CDN77
- Netlify

**Comment by nullchinchilla** [comment]
More users are reporting this issue. v0.12.0 will implement both ticket caching and CDN77.

**Comment by nullchinchilla** [comment]
v0.11.1 adds two more fronts and it seems to have solved most issues.

**Comment by dyhack** [comment]
thanks
